# Generated by Django 5.2.17 on 2026-09-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDeAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('codigo_hash', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expira_em', models.DateTimeField()),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('anulado_em', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'código de acesso',
                'verbose_name_plural': 'códigos de acesso',
                'ordering': ['-criado_em'],
            },
        ),
    ]
