# Generated by Django 5.2.17 on 2026-09-22 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeiroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passeio_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primeiro_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'primeiro acesso',
                'verbose_name_plural': 'primeiros acessos',
            },
        ),
    ]
