# Generated by Django 5.2.17 on 2026-10-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_primeiroacesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='primeiroacesso',
            name='novidades_vistas',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
