# Generated by Django 5.2.17 on 2026-09-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_projetos_arquivo_e_exclusao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['position', '-updated_at'], 'verbose_name': 'conversa', 'verbose_name_plural': 'conversas'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
