# Generated by Django 5.2.17 on 2026-09-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_alter_conversation_options_conversation_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='canal',
            field=models.CharField(choices=[('web', 'Chat web'), ('whatsapp', 'WhatsApp')], default='web', db_default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='whatsapp_jid',
            field=models.CharField(blank=True, db_default='', db_index=True, max_length=80),
        ),
    ]
