# Generated by Django 5.2.17 on 2026-09-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('sql', models.TextField()),
                ('reference_query_id', models.CharField(blank=True, max_length=20)),
                ('guard_result', models.CharField(choices=[('approved', 'Aprovada pelo validador'), ('rejected', 'Recusada pelo validador')], max_length=20)),
                ('guard_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_executed', 'Não executada'), ('success', 'Executada'), ('error', 'Erro do banco'), ('timeout', 'Tempo esgotado')], default='not_executed', max_length=20)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('truncated', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('result_sample', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_runs', to='ai_orchestrator.aireply')),
            ],
            options={
                'verbose_name': 'consulta executada',
                'verbose_name_plural': 'consultas executadas',
                'ordering': ['id'],
            },
        ),
    ]
