# Generated by Django 5.2.17 on 2026-09-18 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
        ('messaging', '0002_resposta_ligada_a_pergunta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.TextField()),
                ('status', models.CharField(choices=[('ok', 'Gerada'), ('error', 'Falhou')], max_length=10)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('truncated', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='messaging.message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'planilha exportada',
                'verbose_name_plural': 'planilhas exportadas',
                'ordering': ['-id'],
            },
        ),
    ]
