# Generated by Django 5.2.17 on 2026-09-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('answered', 'Respondeu com dado'), ('empty_result', 'Consulta sem linhas'), ('clarify', 'Pediu esclarecimento'), ('unknown', 'Não sabe'), ('out_of_scope', 'Fora de escopo'), ('failed', 'Falha da IA ou do banco')], max_length=20)),
                ('rule', models.CharField(blank=True, max_length=60)),
                ('reply_text', models.TextField(blank=True)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('catalog_hash', models.CharField(blank=True, max_length=64)),
                ('tokens_input', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_output', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reply', to='messaging.message')),
            ],
            options={
                'verbose_name': 'resposta da IA',
                'verbose_name_plural': 'respostas da IA',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('plan', 'Planejamento'), ('fix', 'Correção da consulta'), ('answer', 'Redação'), ('rewrite', 'Reescrita da resposta')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('tokens_input', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_output', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='ai_orchestrator.aireply')),
            ],
            options={
                'verbose_name': 'chamada ao modelo',
                'verbose_name_plural': 'chamadas ao modelo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('resolved', 'Resolvida')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_gaps', to='messaging.message')),
            ],
            options={
                'verbose_name': 'lacuna do catálogo',
                'verbose_name_plural': 'lacunas do catálogo',
                'ordering': ['-id'],
            },
        ),
    ]
