# Generated by Django 5.2.17 on 2026-09-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireply',
            name='decision',
            field=models.CharField(choices=[('answered', 'Respondeu com dado'), ('empty_result', 'Consulta sem linhas'), ('clarify', 'Pediu esclarecimento'), ('unknown', 'Não sabe'), ('out_of_scope', 'Fora de escopo'), ('conversation', 'Conversa sem consulta'), ('failed', 'Falha da IA ou do banco')], max_length=20),
        ),
    ]
