# Generated by Django 5.2.17 on 2026-09-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0002_decisao_conversa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicall',
            name='stage',
            field=models.CharField(choices=[('plan', 'Planejamento'), ('fix', 'Correção da consulta'), ('answer', 'Redação'), ('rewrite', 'Reescrita da resposta'), ('image', 'Leitura de imagem')], max_length=20),
        ),
        migrations.AlterField(
            model_name='aireply',
            name='decision',
            field=models.CharField(choices=[('answered', 'Respondeu com dado'), ('empty_result', 'Consulta sem linhas'), ('clarify', 'Pediu esclarecimento'), ('unknown', 'Não sabe'), ('out_of_scope', 'Fora de escopo'), ('conversation', 'Conversa sem consulta'), ('image_reading', 'Leitura de imagem'), ('failed', 'Falha da IA ou do banco')], max_length=20),
        ),
    ]
