# Generated by Django 5.2.17 on 2026-09-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0003_leitura_de_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicall',
            name='stage',
            field=models.CharField(choices=[('plan', 'Planejamento'), ('fix', 'Correção da consulta'), ('answer', 'Redação'), ('rewrite', 'Reescrita da resposta'), ('image', 'Leitura de imagem'), ('investigate', 'Rodada de investigação')], max_length=20),
        ),
    ]
