# Generated by Django 5.2.17 on 2026-09-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0005_alter_aireply_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicall',
            name='stage',
            field=models.CharField(choices=[('plan', 'Planejamento'), ('fix', 'Correção da consulta'), ('answer', 'Redação'), ('rewrite', 'Reescrita da resposta'), ('image', 'Leitura de imagem'), ('investigate', 'Rodada de investigação'), ('self_check', 'Autocrítica do seguimento')], max_length=20),
        ),
    ]
