# Generated by Django 5.2.17 on 2026-10-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0006_etapa_autocritica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicall',
            name='stage',
            field=models.CharField(choices=[('plan', 'Planejamento'), ('fix', 'Correção da consulta'), ('answer', 'Redação'), ('rewrite', 'Reescrita da resposta'), ('image', 'Leitura de imagem'), ('investigate', 'Rodada de investigação'), ('self_check', 'Autocrítica do seguimento'), ('explore', 'Consulta depois do reconhecimento')], max_length=20),
        ),
    ]
