# Generated by Django 5.2.17 on 2026-10-06 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0007_etapa_de_reconhecimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinicioDeLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feito_em', models.DateTimeField(auto_now_add=True)),
                ('feito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinicios_de_limite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reinício de limite',
                'verbose_name_plural': 'reinícios de limite',
                'ordering': ['-feito_em'],
            },
        ),
    ]
