# Generated by Django 5.2.17 on 2026-09-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Pergunta'), ('out', 'Resposta')], max_length=10)),
                ('content', models.TextField()),
                ('client_message_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('received', 'Recebida'), ('processing', 'Em processamento'), ('processed', 'Processada'), ('sent', 'Entregue'), ('failed', 'Falhou')], default='received', max_length=20)),
                ('delivery_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['conversation', 'id'], name='messaging_m_convers_f5b548_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'client_message_id'), name='unique_client_message_id_por_conversa')],
            },
        ),
    ]
