# Generated by Django 5.2.17 on 2026-09-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_resposta_ligada_a_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='anexo_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='anexo_resposta_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='anexo_resposta_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='anexo_resumo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='anexo_tipo',
            field=models.CharField(blank=True, choices=[('planilha', 'Planilha'), ('imagem', 'Imagem')], max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='anexo_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
