# Generated by Django 5.2.17 on 2026-09-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_anexo_sem_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='anexo_miniatura',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
