# Generated by Django 5.2.17 on 2026-09-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_miniatura_da_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('received', 'Recebida'), ('processing', 'Em processamento'), ('processed', 'Processada'), ('sent', 'Entregue'), ('failed', 'Falhou'), ('cancelled', 'Interrompida')], default='received', max_length=20),
        ),
    ]
