# Generated by Django 5.2.17 on 2026-09-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_message_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(choices=[('up', 'Útil'), ('down', 'Errada')], max_length=10)),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caso_exportado_em', models.DateTimeField(blank=True, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='messaging.message')),
            ],
            options={
                'verbose_name': 'avaliação de resposta',
                'verbose_name_plural': 'avaliações de resposta',
                'ordering': ['-id'],
            },
        ),
    ]
