# Generated by Django 5.2.17 on 2026-09-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_avaliacao_da_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='autor_externo',
            field=models.CharField(blank=True, db_default='', max_length=40),
        ),
        migrations.AddField(
            model_name='message',
            name='autor_nome',
            field=models.CharField(blank=True, db_default='', max_length=120),
        ),
    ]
