# Generated by Django 5.2.17 on 2026-10-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_canal_da_conversa'),
        ('messaging', '0007_autor_no_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoDaConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('papel', models.CharField(choices=[('entrada', 'Enviado pela pessoa'), ('saida', 'Devolvido pelo Jarvis')], max_length=10)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('chave', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='conversations.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos', to='messaging.message')),
            ],
            options={
                'verbose_name': 'arquivo da conversa',
                'verbose_name_plural': 'arquivos da conversa',
                'ordering': ['-id'],
            },
        ),
    ]
