# Generated by Django 5.2.17 on 2026-09-23 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0007_autor_no_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Com DDI e DDD, só dígitos: 5511999998888.', max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_whatsapp', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'contato do WhatsApp',
                'verbose_name_plural': 'contatos do WhatsApp',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='EnvioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externo_id', models.CharField(max_length=100, unique=True)),
                ('jid', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('documento', 'Documento'), ('aviso', 'Aviso')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_whatsapp', to='messaging.message')),
            ],
            options={
                'verbose_name': 'envio no WhatsApp',
                'verbose_name_plural': 'envios no WhatsApp',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GrupoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(help_text='Identificador do grupo no WhatsApp (termina em @g.us). Aparece no log e na página de conexão.', max_length=80, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('limite_diario', models.PositiveIntegerField(default=30)),
                ('limite_semanal', models.PositiveIntegerField(default=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupo_whatsapp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grupo do WhatsApp',
                'verbose_name_plural': 'grupos do WhatsApp',
                'ordering': ['nome'],
            },
        ),
    ]
