# Generated by Django 5.2.17 on 2026-09-24 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contatowhatsapp',
            name='nome',
            field=models.CharField(blank=True, db_default='', default='', help_text='Como a pessoa aparece no Admin e no usuário técnico.', max_length=120),
        ),
        migrations.AlterField(
            model_name='contatowhatsapp',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Opcional. Vazio: o Jarvis cria um usuário técnico para este número.', on_delete=django.db.models.deletion.CASCADE, related_name='contatos_whatsapp', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
